BEGIN;
INSERT INTO clients (name, balance) VALUES ('Cliente 1', 100.00);
UPDATE clients SET balance = balance + 50 WHERE id = 1;
END;
BEGIN;
INSERT INTO clients (name, balance) VALUES ('Cliente 2', 200.00);
UPDATE clients SET balance = balance + 50 WHERE id = 2;
END;
BEGIN;
INSERT INTO clients (name, balance) VALUES ('Cliente 3', 300.00);
UPDATE clients SET balance = balance + 50 WHERE id = 2;
END;
BEGIN;
INSERT INTO clients (name, balance) VALUES ('Cliente 4', 400.00);
UPDATE clients SET balance = balance + 50 WHERE id = 3;
BEGIN;
INSERT INTO clients (name, balance) VALUES ('Cliente 6', 600.00); 
DELETE FROM clients WHERE id = 3;